{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.halyardName }}
  name: {{ .Values.serviceAccount.halyardName }}
  {{- else }}
  name: {{ template "spinnaker.fullname" . }}-halyard
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    snappyflow/compname: spinnaker
    snappyflow/appname: cicd-stage
{{ include "spinnaker.standard-labels" . | indent 4 }}
{{- end }}
