apiVersion: v1
kind: Service
metadata:
  name: {{ template "spinnaker.fullname" . }}-halyard
  labels:
    snappyflow/compname: spinnaker
    snappyflow/appname: cicd-stage
{{ include "spinnaker.standard-labels" . | indent 4 }}
    component: halyard
spec:
  ports:
  - port: 8064
    name: daemon
  clusterIP: None
  selector:
    app: {{ template "spinnaker.fullname" . }}
    component: halyard
